export const baseUrl = "https://student-details-management-web.herokuapp.com/api";
// export const baseUrl = "http://localhost:8080/api";
export const authUrl = "/authenticate";
export const saveUrl = "/save-student";
export const updateUrl = "/update-details/{key}";
export const deleteUrl = "/remove-details/{key}";
export const listUrl = "/student-list/{type}";
export const listAllUrl = "/student-details/export/{type}";
export const detailUrl = "/student-details/{key}";